In [1]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

## Importing the Necessary Libraries and the Dataset

In [2]:
import pandas as pd
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import  train_test_split
from sklearn.preprocessing import StandardScaler

url = "https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv"

columns = ["Pregnancies",
           'Glucose',
           'BloodPressure',
           'SkinThickness',
           'Insulin',
           'BMI',
           'DiabetesPedigreeFunction',
           'age',
           'Outcome']
df = pd.read_csv(url, names=columns, skiprows=1)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

## Preprocessing Using SMOTE

The class distribution confirms the imbalance. To handle this, we can use an oversampling technique like SMOTE (Synthetic Minority Over-sampling Technique) to create synthetic samples for the minority class.

In [3]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
age                         0
Outcome                     0
dtype: int64

In [4]:
import numpy as np
cols_with_missing_vals = ['Glucose',"BloodPressure","Insulin","BMI"]
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0,np.nan) ## Converting all the zero values into nan Values
df.fillna(df.mean(),inplace = True) ## Converting all the Nan Values with their mean values

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
age                         0
Outcome                     0
dtype: int64

In [6]:
X = df.drop('Outcome',axis = 1)
y = df['Outcome']

In [7]:
X_train,x_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state = 42)

In [8]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_train, y_train = sm.fit_resample(X_train, y_train)

print('Class distribution after SMOTE:')
display(y_train.value_counts())

Class distribution after SMOTE:

Outcome
0    401
1    401
Name: count, dtype: int64

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
x_test = scaler.transform(x_test)

## Applying the Model using HyperParameter Tuning using Optuna

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


def objective(trail):
  ''' Creating the Required Values of both the Hyper Parameters'''
  n_estimators = trail.suggest_int('n_estimators',50,300) ## Values of N-Estimators Ranges Between 50 and 300
  max_depth = trail.suggest_int('max_depth',3,20) ## Values of Max-Depth Ranges between 3 and 20

  ''' Creating a Random Forest Classifier with the suggested Parameters'''
  ''' Basically Creating a WorkSpace'''
  model = RandomForestClassifier(
      n_estimators= n_estimators,
      max_depth = max_depth,
      random_state = 42
  )
  ''' Calculating the Cross Validation Score'''
  score = cross_val_score(model,X_train,y_train,cv = 3,scoring = 'accuracy').mean() ## Multiple Accracy Scores's Mean
  return score

In [11]:
''' Creating a New Study'''

'''Using the Sampler as Tree Parzen Estimator''' ## (By Default Bayseian Search)
study = optuna.create_study(
    direction = 'maximize', ## Helps in identifying the next Set of Points
    sampler = optuna.samplers.TPESampler(),
)

study.optimize(objective, n_trials = 50)

[I 2026-06-30 05:59:31,036] A new study created in memory with name: no-name-d9801560-ad9e-4590-ad88-1b52c6ee74a3
[I 2026-06-30 05:59:33,025] Trial 0 finished with value: 0.8291827379954162 and parameters: {'n_estimators': 233, 'max_depth': 20}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:34,048] Trial 1 finished with value: 0.8217060763597742 and parameters: {'n_estimators': 62, 'max_depth': 18}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:35,870] Trial 2 finished with value: 0.824193638548829 and parameters: {'n_estimators': 93, 'max_depth': 13}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:38,290] Trial 3 finished with value: 0.8242029552611475 and parameters: {'n_estimators': 150, 'max_depth': 18}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:43,386] Trial 4 finished with value: 0.8167169769131869 and parameters: {'n_estimators': 237, 'max_depth': 7}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:47,328] Trial 5 finished with value: 0.7967372873460413 and parameters: {'n_estimators': 278, 'max_depth': 4}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:51,151] Trial 6 finished with value: 0.8279296401885703 and parameters: {'n_estimators': 236, 'max_depth': 16}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:52,064] Trial 7 finished with value: 0.8217153930720927 and parameters: {'n_estimators': 60, 'max_depth': 12}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:57,944] Trial 8 finished with value: 0.8054763635008478 and parameters: {'n_estimators': 277, 'max_depth': 5}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 05:59:59,506] Trial 9 finished with value: 0.8267091508748393 and parameters: {'n_estimators': 126, 'max_depth': 17}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 06:00:02,613] Trial 10 finished with value: 0.8229405407419829 and parameters: {'n_estimators': 182, 'max_depth': 9}. Best is trial 0 with value: 0.8291827379954162.
[I 2026-06-30 06:00:06,057] Trial 11 finished with value: 0.8291873963515753 and parameters: {'n_estimators': 215, 'max_depth': 20}. Best is trial 11 with value: 0.8291873963515753.
[I 2026-06-30 06:00:11,668] Trial 12 finished with value: 0.8266998341625208 and parameters: {'n_estimators': 210, 'max_depth': 20}. Best is trial 11 with value: 0.8291873963515753.
[I 2026-06-30 06:00:15,065] Trial 13 finished with value: 0.8266905174502021 and parameters: {'n_estimators': 189, 'max_depth': 20}. Best is trial 11 with value: 0.8291873963515753.
[I 2026-06-30 06:00:18,670] Trial 14 finished with value: 0.8266905174502021 and parameters: {'n_estimators': 246, 'max_depth': 15}. Best is trial 11 with value: 0.8291873963515753.
[I 2026-06-30 06:00:21,124] Trial 15 finished with value: 0.8304311774461027 and parameters: {'n_estimators': 164, 'max_depth': 20}. Best is trial 15 with value: 0.8304311774461027.
[I 2026-06-30 06:00:25,156] Trial 16 finished with value: 0.8291873963515756 and parameters: {'n_estimators': 153, 'max_depth': 14}. Best is trial 15 with value: 0.8304311774461027.
[I 2026-06-30 06:00:27,391] Trial 17 finished with value: 0.8241982969049881 and parameters: {'n_estimators': 131, 'max_depth': 11}. Best is trial 15 with value: 0.8304311774461027.
[I 2026-06-30 06:00:29,840] Trial 18 finished with value: 0.827943615257048 and parameters: {'n_estimators': 162, 'max_depth': 14}. Best is trial 15 with value: 0.8304311774461027.
[I 2026-06-30 06:00:31,089] Trial 19 finished with value: 0.8154638791063409 and parameters: {'n_estimators': 101, 'max_depth': 9}. Best is trial 15 with value: 0.8304311774461027.
[I 2026-06-30 06:00:33,194] Trial 20 finished with value: 0.8279203234762518 and parameters: {'n_estimators': 169, 'max_depth': 10}. Best is trial 15 with value: 0.8304311774461027.
[I 2026-06-30 06:00:37,798] Trial 21 finished with value: 0.8291827379954162 and parameters: {'n_estimators': 206, 'max_depth': 18}. Best is trial 15 with value: 0.8304311774461027.
[I 2026-06-30 06:00:40,070] Trial 22 finished with value: 0.8329327147036354 and parameters: {'n_estimators': 138, 'max_depth': 16}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:41,730] Trial 23 finished with value: 0.8266998341625208 and parameters: {'n_estimators': 136, 'max_depth': 15}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:42,972] Trial 24 finished with value: 0.8229545158104608 and parameters: {'n_estimators': 109, 'max_depth': 13}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:44,590] Trial 25 finished with value: 0.8279389569008888 and parameters: {'n_estimators': 151, 'max_depth': 16}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:45,855] Trial 26 finished with value: 0.8229545158104608 and parameters: {'n_estimators': 84, 'max_depth': 17}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:48,059] Trial 27 finished with value: 0.8291873963515756 and parameters: {'n_estimators': 183, 'max_depth': 14}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:50,316] Trial 28 finished with value: 0.824193638548829 and parameters: {'n_estimators': 111, 'max_depth': 19}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:53,441] Trial 29 finished with value: 0.8304404941584212 and parameters: {'n_estimators': 145, 'max_depth': 16}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:56,092] Trial 30 finished with value: 0.8291873963515753 and parameters: {'n_estimators': 120, 'max_depth': 16}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:00:58,909] Trial 31 finished with value: 0.8266951758063614 and parameters: {'n_estimators': 151, 'max_depth': 14}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:02,809] Trial 32 finished with value: 0.8291873963515753 and parameters: {'n_estimators': 168, 'max_depth': 18}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:07,008] Trial 33 finished with value: 0.8217060763597742 and parameters: {'n_estimators': 144, 'max_depth': 13}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:08,111] Trial 34 finished with value: 0.8229498574543016 and parameters: {'n_estimators': 83, 'max_depth': 17}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:10,353] Trial 35 finished with value: 0.8279389569008888 and parameters: {'n_estimators': 192, 'max_depth': 19}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:12,282] Trial 36 finished with value: 0.8266812007378835 and parameters: {'n_estimators': 169, 'max_depth': 12}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:14,795] Trial 37 finished with value: 0.827943615257048 and parameters: {'n_estimators': 140, 'max_depth': 15}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:17,358] Trial 38 finished with value: 0.8316796168967895 and parameters: {'n_estimators': 159, 'max_depth': 16}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:19,333] Trial 39 finished with value: 0.8266905174502023 and parameters: {'n_estimators': 119, 'max_depth': 19}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:20,226] Trial 40 finished with value: 0.8229498574543016 and parameters: {'n_estimators': 81, 'max_depth': 18}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:22,401] Trial 41 finished with value: 0.8291873963515753 and parameters: {'n_estimators': 155, 'max_depth': 16}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:24,210] Trial 42 finished with value: 0.8254560530679934 and parameters: {'n_estimators': 133, 'max_depth': 15}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:27,947] Trial 43 finished with value: 0.8316796168967895 and parameters: {'n_estimators': 300, 'max_depth': 17}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:32,064] Trial 44 finished with value: 0.831670300184471 and parameters: {'n_estimators': 261, 'max_depth': 17}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:35,939] Trial 45 finished with value: 0.8329187396351575 and parameters: {'n_estimators': 299, 'max_depth': 17}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:39,121] Trial 46 finished with value: 0.8291827379954162 and parameters: {'n_estimators': 298, 'max_depth': 17}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:41,474] Trial 47 finished with value: 0.8304265190899436 and parameters: {'n_estimators': 261, 'max_depth': 18}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:46,672] Trial 48 finished with value: 0.7867590884528667 and parameters: {'n_estimators': 300, 'max_depth': 3}. Best is trial 22 with value: 0.8329327147036354.
[I 2026-06-30 06:01:50,546] Trial 49 finished with value: 0.831670300184471 and parameters: {'n_estimators': 286, 'max_depth': 17}. Best is trial 22 with value: 0.8329327147036354.

In [12]:
print(f"Best Trial Parameters: {study.best_trial.params}")
print(f"Best Trial Value: {study.best_trial.value}")

Best Trial Parameters: {'n_estimators': 138, 'max_depth': 16}
Best Trial Value: 0.8329327147036354

## Evaluation

In [13]:
from sklearn.metrics import accuracy_score,classification_report
bestModel = RandomForestClassifier(
    n_estimators= study.best_trial.params['n_estimators'],
    max_depth = study.best_trial.params['max_depth'],
    random_state = 42
)

In [14]:
bestModel.fit(X_train,y_train)

RandomForestClassifier(max_depth=16, n_estimators=138, random_state=42)

In [15]:
y_pred = bestModel.predict(x_test)

In [16]:
testAccuracy = accuracy_score(y_test,y_pred)
print(f"Test Accuracy: {testAccuracy}")

Test Accuracy: 0.7662337662337663

## Samplers in Optuna

#### Building the Random Search Using Optuna Without Sklearn

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


def objective(trail):
  ''' Creating the Required Values of both the Hyper Parameters'''
  n_estimators = trail.suggest_int('n_estimators',50,300) ## Values of N-Estimators Ranges Between 50 and 300
  max_depth = trail.suggest_int('max_depth',3,20) ## Values of Max-Depth Ranges between 3 and 20

  ''' Creating a Random Forest Classifier with the suggested Parameters'''
  ''' Basically Creating a WorkSpace'''
  model = RandomForestClassifier(
      n_estimators= n_estimators,
      max_depth = max_depth,
      random_state = 42
  )
  ''' Calculating the Cross Validation Score'''
  score = cross_val_score(model,X_train,y_train,cv = 3,scoring = 'accuracy').mean() ## Multiple Accracy Scores's Mean
  return score

In [18]:
''' Creating a New Study'''

'''Using the Sampler as Tree Parzen Estimator''' ## (By Default Bayseian Search)
study = optuna.create_study(
    direction = 'maximize', ## Helps in identifying the next Set of Points
    sampler = optuna.samplers.RandomSampler(),
)

study.optimize(objective, n_trials = 50)

[I 2026-06-30 06:01:51,188] A new study created in memory with name: no-name-a1c92d9d-c851-4992-9918-f8dbee9349b1
[I 2026-06-30 06:01:51,865] Trial 0 finished with value: 0.7817746473624387 and parameters: {'n_estimators': 55, 'max_depth': 3}. Best is trial 0 with value: 0.7817746473624387.
[I 2026-06-30 06:01:53,343] Trial 1 finished with value: 0.8217060763597742 and parameters: {'n_estimators': 117, 'max_depth': 15}. Best is trial 1 with value: 0.8217060763597742.
[I 2026-06-30 06:01:57,624] Trial 2 finished with value: 0.8304311774461027 and parameters: {'n_estimators': 292, 'max_depth': 19}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:00,420] Trial 3 finished with value: 0.8266951758063614 and parameters: {'n_estimators': 208, 'max_depth': 19}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:02,081] Trial 4 finished with value: 0.8167123185570276 and parameters: {'n_estimators': 247, 'max_depth': 8}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:04,172] Trial 5 finished with value: 0.8291780796392568 and parameters: {'n_estimators': 279, 'max_depth': 15}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:05,739] Trial 6 finished with value: 0.8304265190899435 and parameters: {'n_estimators': 224, 'max_depth': 16}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:06,937] Trial 7 finished with value: 0.796732628989882 and parameters: {'n_estimators': 205, 'max_depth': 4}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:08,244] Trial 8 finished with value: 0.819195222389923 and parameters: {'n_estimators': 194, 'max_depth': 8}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:08,747] Trial 9 finished with value: 0.8229591741666201 and parameters: {'n_estimators': 71, 'max_depth': 13}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:10,885] Trial 10 finished with value: 0.8241843218365102 and parameters: {'n_estimators': 223, 'max_depth': 12}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:13,245] Trial 11 finished with value: 0.815463879106341 and parameters: {'n_estimators': 261, 'max_depth': 6}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:14,045] Trial 12 finished with value: 0.8117139023981217 and parameters: {'n_estimators': 120, 'max_depth': 7}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:14,582] Trial 13 finished with value: 0.8216967596474557 and parameters: {'n_estimators': 73, 'max_depth': 10}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:16,495] Trial 14 finished with value: 0.8266951758063614 and parameters: {'n_estimators': 277, 'max_depth': 14}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:16,936] Trial 15 finished with value: 0.8217153930720927 and parameters: {'n_estimators': 58, 'max_depth': 20}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:18,402] Trial 16 finished with value: 0.8229312240296643 and parameters: {'n_estimators': 220, 'max_depth': 8}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:19,720] Trial 17 finished with value: 0.8179467829392365 and parameters: {'n_estimators': 204, 'max_depth': 6}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:20,721] Trial 18 finished with value: 0.8241889801926696 and parameters: {'n_estimators': 144, 'max_depth': 10}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:22,222] Trial 19 finished with value: 0.8304311774461027 and parameters: {'n_estimators': 213, 'max_depth': 19}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:22,829] Trial 20 finished with value: 0.8229545158104608 and parameters: {'n_estimators': 85, 'max_depth': 16}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:24,032] Trial 21 finished with value: 0.825432761287197 and parameters: {'n_estimators': 112, 'max_depth': 12}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:24,587] Trial 22 finished with value: 0.8254560530679934 and parameters: {'n_estimators': 51, 'max_depth': 16}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:25,259] Trial 23 finished with value: 0.78054018298023 and parameters: {'n_estimators': 77, 'max_depth': 3}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:27,217] Trial 24 finished with value: 0.8254374196433562 and parameters: {'n_estimators': 245, 'max_depth': 13}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:28,722] Trial 25 finished with value: 0.814210781299495 and parameters: {'n_estimators': 237, 'max_depth': 6}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:30,488] Trial 26 finished with value: 0.8304311774461027 and parameters: {'n_estimators': 249, 'max_depth': 15}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:31,546] Trial 27 finished with value: 0.8266951758063614 and parameters: {'n_estimators': 147, 'max_depth': 14}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:32,523] Trial 28 finished with value: 0.8167123185570276 and parameters: {'n_estimators': 145, 'max_depth': 7}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:33,080] Trial 29 finished with value: 0.8154638791063409 and parameters: {'n_estimators': 81, 'max_depth': 9}. Best is trial 2 with value: 0.8304311774461027.
[I 2026-06-30 06:02:35,120] Trial 30 finished with value: 0.8341671790858441 and parameters: {'n_estimators': 289, 'max_depth': 17}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:37,174] Trial 31 finished with value: 0.7967372873460413 and parameters: {'n_estimators': 279, 'max_depth': 4}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:39,032] Trial 32 finished with value: 0.8167076602008683 and parameters: {'n_estimators': 195, 'max_depth': 7}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:39,557] Trial 33 finished with value: 0.8254420779995155 and parameters: {'n_estimators': 73, 'max_depth': 13}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:40,518] Trial 34 finished with value: 0.8067201445953751 and parameters: {'n_estimators': 156, 'max_depth': 5}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:41,788] Trial 35 finished with value: 0.796732628989882 and parameters: {'n_estimators': 216, 'max_depth': 4}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:43,843] Trial 36 finished with value: 0.8254374196433564 and parameters: {'n_estimators': 297, 'max_depth': 11}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:44,578] Trial 37 finished with value: 0.8266951758063614 and parameters: {'n_estimators': 102, 'max_depth': 19}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:45,806] Trial 38 finished with value: 0.8204529785529283 and parameters: {'n_estimators': 179, 'max_depth': 11}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:47,059] Trial 39 finished with value: 0.8304265190899436 and parameters: {'n_estimators': 179, 'max_depth': 15}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:47,577] Trial 40 finished with value: 0.8067248029515346 and parameters: {'n_estimators': 81, 'max_depth': 6}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:48,828] Trial 41 finished with value: 0.8279203234762517 and parameters: {'n_estimators': 104, 'max_depth': 10}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:49,517] Trial 42 finished with value: 0.8217107347159334 and parameters: {'n_estimators': 61, 'max_depth': 16}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:50,763] Trial 43 finished with value: 0.8191998807460824 and parameters: {'n_estimators': 121, 'max_depth': 9}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:53,126] Trial 44 finished with value: 0.8291734212830977 and parameters: {'n_estimators': 277, 'max_depth': 13}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:55,061] Trial 45 finished with value: 0.8254374196433564 and parameters: {'n_estimators': 285, 'max_depth': 11}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:56,336] Trial 46 finished with value: 0.7842761846199714 and parameters: {'n_estimators': 130, 'max_depth': 3}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:57,237] Trial 47 finished with value: 0.8229591741666201 and parameters: {'n_estimators': 126, 'max_depth': 15}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:58,425] Trial 48 finished with value: 0.7954841895391954 and parameters: {'n_estimators': 203, 'max_depth': 4}. Best is trial 30 with value: 0.8341671790858441.
[I 2026-06-30 06:02:59,862] Trial 49 finished with value: 0.8304265190899436 and parameters: {'n_estimators': 203, 'max_depth': 16}. Best is trial 30 with value: 0.8341671790858441.

In [19]:
from sklearn.metrics import accuracy_score,classification_report
bestModel = RandomForestClassifier(
    n_estimators= study.best_trial.params['n_estimators'],
    max_depth = study.best_trial.params['max_depth'],
    random_state = 42
)
bestModel.fit(X_train,y_train)
y_pred = bestModel.predict(x_test)
testAccuracy = accuracy_score(y_test,y_pred)
print(f"Test Accuracy: {testAccuracy}")

Test Accuracy: 0.7662337662337663

#### Building the Grid| Search Using Optuna Without Sklearn

In [20]:
search_space = {
    'n_estimators': [50, 100, 150, 200, 250, 300],
    'max_depth': [3, 5, 7, 9]
}

In [22]:
study = optuna.create_study(
    direction='maximize',
    sampler=optuna.samplers.GridSampler(search_space)
)
study.optimize(objective)

[I 2026-06-30 06:12:18,536] A new study created in memory with name: no-name-784c3902-8164-45b0-a38b-581af62e44b0
[I 2026-06-30 06:12:22,003] Trial 0 finished with value: 0.8042279240501612 and parameters: {'n_estimators': 300, 'max_depth': 5}. Best is trial 0 with value: 0.8042279240501612.
[I 2026-06-30 06:12:24,979] Trial 1 finished with value: 0.8042279240501612 and parameters: {'n_estimators': 250, 'max_depth': 5}. Best is trial 0 with value: 0.8042279240501612.
[I 2026-06-30 06:12:30,214] Trial 2 finished with value: 0.8204483201967689 and parameters: {'n_estimators': 250, 'max_depth': 9}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:32,100] Trial 3 finished with value: 0.8167123185570276 and parameters: {'n_estimators': 150, 'max_depth': 7}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:33,893] Trial 4 finished with value: 0.8204483201967689 and parameters: {'n_estimators': 150, 'max_depth': 9}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:34,948] Trial 5 finished with value: 0.7842761846199714 and parameters: {'n_estimators': 100, 'max_depth': 3}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:36,125] Trial 6 finished with value: 0.8042465574747983 and parameters: {'n_estimators': 100, 'max_depth': 7}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:42,002] Trial 7 finished with value: 0.8191998807460824 and parameters: {'n_estimators': 300, 'max_depth': 9}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:45,762] Trial 8 finished with value: 0.8154685374625003 and parameters: {'n_estimators': 250, 'max_depth': 7}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:47,745] Trial 9 finished with value: 0.8017263867926285 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:48,252] Trial 10 finished with value: 0.7967419457022006 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:51,406] Trial 11 finished with value: 0.8117325358227588 and parameters: {'n_estimators': 300, 'max_depth': 7}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:53,401] Trial 12 finished with value: 0.7880075279035533 and parameters: {'n_estimators': 250, 'max_depth': 3}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:54,744] Trial 13 finished with value: 0.7880168446158718 and parameters: {'n_estimators': 150, 'max_depth': 3}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:56,436] Trial 14 finished with value: 0.7867590884528667 and parameters: {'n_estimators': 300, 'max_depth': 3}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:56,784] Trial 15 finished with value: 0.8092496319898634 and parameters: {'n_estimators': 50, 'max_depth': 9}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:58,001] Trial 16 finished with value: 0.8042186073378427 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:58,629] Trial 17 finished with value: 0.8029748262433153 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:12:59,338] Trial 18 finished with value: 0.8154592207501817 and parameters: {'n_estimators': 100, 'max_depth': 9}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:13:00,476] Trial 19 finished with value: 0.7830277451692846 and parameters: {'n_estimators': 200, 'max_depth': 3}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:13:00,771] Trial 20 finished with value: 0.779287085173384 and parameters: {'n_estimators': 50, 'max_depth': 3}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:13:02,128] Trial 21 finished with value: 0.8204483201967689 and parameters: {'n_estimators': 200, 'max_depth': 9}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:13:03,451] Trial 22 finished with value: 0.8154592207501817 and parameters: {'n_estimators': 200, 'max_depth': 7}. Best is trial 2 with value: 0.8204483201967689.
[I 2026-06-30 06:13:03,803] Trial 23 finished with value: 0.804241899118639 and parameters: {'n_estimators': 50, 'max_depth': 7}. Best is trial 2 with value: 0.8204483201967689.

In [23]:
from sklearn.metrics import accuracy_score,classification_report
bestModel = RandomForestClassifier(
    n_estimators= study.best_trial.params['n_estimators'],
    max_depth = study.best_trial.params['max_depth'],
    random_state = 42
)
bestModel.fit(X_train,y_train)
y_pred = bestModel.predict(x_test)
testAccuracy = accuracy_score(y_test,y_pred)
print(f"Test Accuracy: {testAccuracy}")

Test Accuracy: 0.7727272727272727

## Optuna Visualizations

In [24]:
from optuna.visualization import plot_optimization_history,plot_parallel_coordinate,plot_slice,plot_contour,plot_param_importances
plot_optimization_history(study).show()
''' Graph Bteweem the Objective Value and Trilas'''

' Graph Bteweem the Objective Value and Trilas'

In [25]:
plot_parallel_coordinate(study).show()

In [26]:
plot_slice(study).show()

In [27]:
plot_contour(study).show()

In [28]:
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [29]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [30]:
def objective(trial):
  classifier = trial.suggest_categorical('classifier',['SVM','RandomForest','GradientBoosting','LogisticRegression'])

  if classifier == 'SVM':
    c = trial.suggest_float('C',0.1,100,log = True)
    kernel = trial.suggest_categorical('kernel',['linear','rbf','poly','sigmoid'])
    gamma = trial.suggest_categorical('gamma',['scale','auto'])
    model = SVC(C = c,kernel = kernel,gamma = gamma,random_state = 42)

  elif classifier == 'RandomForest':
    nestimators = trial.suggest_int('n_estimators',50,300)
    max_depth = trial.suggest_int('max_depth',3,20)
    min_split = trial.suggest_int('min_split',2,10)
    min_leaf = trial.suggest_int('min_leaf',1,10)
    model = RandomForestClassifier(
        n_estimators = nestimators,
        max_depth = max_depth,
        min_samples_split=min_split,
        min_samples_leaf=min_leaf,
        random_state = 42
    )

  elif classifier == 'GradientBoosting':
    n_estimators = trial.suggest_int('n_estimators',50,300) # Corrected typo from nestimaotrs
    learning_rate = trial.suggest_float('learning_rate',0.001, 0.3) # Added high argument
    max_depth = trial.suggest_int('max_depth',3,20)
    min_split = trial.suggest_int('min_split',2,10)
    min_leaf = trial.suggest_int('min_leaf',1,1) # min_leaf usually has a range, might want to check this
    model = GradientBoostingClassifier(
        n_estimators = n_estimators,
        learning_rate = learning_rate,
        max_depth = max_depth,
        min_samples_split=min_split,
        min_samples_leaf=min_leaf
    )

  else :
    c = trial.suggest_float('C',0.1,100,log = True)
    max_iter = trial.suggest_int('max_iter',100,1000)
    model = LogisticRegression(
        C = c,
        max_iter = max_iter,
        random_state = 42
    )

  score = cross_val_score(model,X_train,y_train,cv = 3,scoring = 'accuracy').mean()
  return score

In [31]:
study = optuna.create_study(direction= 'maximize')
study.optimize(objective,n_trials = 100)

[I 2026-06-30 06:13:29,080] A new study created in memory with name: no-name-c671e02f-9f59-42ad-b942-8d78cfba7cfb
[I 2026-06-30 06:13:32,452] Trial 0 finished with value: 0.7506568282184584 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 168, 'learning_rate': 0.29215512295243007, 'max_depth': 20, 'min_split': 4, 'min_leaf': 1}. Best is trial 0 with value: 0.7506568282184584.
[I 2026-06-30 06:13:37,134] Trial 1 finished with value: 0.8192138558145601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 250, 'learning_rate': 0.05092108706861579, 'max_depth': 7, 'min_split': 5, 'min_leaf': 1}. Best is trial 1 with value: 0.8192138558145601.
[I 2026-06-30 06:13:37,160] Trial 2 finished with value: 0.7493385134253825 and parameters: {'classifier': 'LogisticRegression', 'C': 42.66146500664712, 'max_iter': 556}. Best is trial 1 with value: 0.8192138558145601.
[I 2026-06-30 06:13:37,249] Trial 3 finished with value: 0.7580915646486668 and parameters: {'classifier': 'SVM', 'C': 1.4104015230481168, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.8192138558145601.
[I 2026-06-30 06:13:37,273] Trial 4 finished with value: 0.7493385134253825 and parameters: {'classifier': 'LogisticRegression', 'C': 95.10008264369303, 'max_iter': 864}. Best is trial 1 with value: 0.8192138558145601.
[I 2026-06-30 06:13:43,313] Trial 5 finished with value: 0.8279482736132073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 276, 'learning_rate': 0.13523030078263878, 'max_depth': 12, 'min_split': 10, 'min_leaf': 1}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:13:43,419] Trial 6 finished with value: 0.7493385134253825 and parameters: {'classifier': 'LogisticRegression', 'C': 2.550035788394573, 'max_iter': 857}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:13:43,461] Trial 7 finished with value: 0.7480900739746957 and parameters: {'classifier': 'LogisticRegression', 'C': 0.24592417403368805, 'max_iter': 705}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:13:43,590] Trial 8 finished with value: 0.7942450668008272 and parameters: {'classifier': 'SVM', 'C': 1.9257614436094244, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:13:43,671] Trial 9 finished with value: 0.6558592803771405 and parameters: {'classifier': 'SVM', 'C': 6.668393586551206, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:13:44,641] Trial 10 finished with value: 0.7942497251569867 and parameters: {'classifier': 'RandomForest', 'n_estimators': 95, 'max_depth': 10, 'min_split': 10, 'min_leaf': 10}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:13:49,745] Trial 11 finished with value: 0.8267138092309986 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 298, 'learning_rate': 0.07836668858891674, 'max_depth': 7, 'min_split': 9, 'min_leaf': 1}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:13:58,207] Trial 12 finished with value: 0.8217153930720927 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 300, 'learning_rate': 0.09626805041825176, 'max_depth': 12, 'min_split': 10, 'min_leaf': 1}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:14:00,425] Trial 13 finished with value: 0.8042791659679133 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 300, 'learning_rate': 0.1596359558201584, 'max_depth': 3, 'min_split': 8, 'min_leaf': 1}. Best is trial 5 with value: 0.8279482736132073.
[I 2026-06-30 06:14:05,524] Trial 14 finished with value: 0.8291873963515753 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 230, 'learning_rate': 0.153211199512633, 'max_depth': 14, 'min_split': 8, 'min_leaf': 1}. Best is trial 14 with value: 0.8291873963515753.
[I 2026-06-30 06:14:06,971] Trial 15 finished with value: 0.8179514412953957 and parameters: {'classifier': 'RandomForest', 'n_estimators': 214, 'max_depth': 16, 'min_split': 7, 'min_leaf': 4}. Best is trial 14 with value: 0.8291873963515753.
[I 2026-06-30 06:14:12,485] Trial 16 finished with value: 0.835401643468053 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 213, 'learning_rate': 0.17863883037901981, 'max_depth': 13, 'min_split': 7, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:16,483] Trial 17 finished with value: 0.8192091974584009 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 189, 'learning_rate': 0.21182178533569052, 'max_depth': 16, 'min_split': 6, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:18,816] Trial 18 finished with value: 0.7718709821678127 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 145, 'learning_rate': 0.20684826491733302, 'max_depth': 15, 'min_split': 2, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:20,391] Trial 19 finished with value: 0.8167076602008683 and parameters: {'classifier': 'RandomForest', 'n_estimators': 232, 'max_depth': 20, 'min_split': 7, 'min_leaf': 4}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:25,218] Trial 20 finished with value: 0.7755743753144392 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 139, 'learning_rate': 0.0029738271099718216, 'max_depth': 13, 'min_split': 8, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:30,278] Trial 21 finished with value: 0.8254607114241527 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 257, 'learning_rate': 0.14939159806164418, 'max_depth': 12, 'min_split': 9, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:35,404] Trial 22 finished with value: 0.8242076136173067 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 207, 'learning_rate': 0.15288526694808902, 'max_depth': 9, 'min_split': 8, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:40,131] Trial 23 finished with value: 0.8229498574543016 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 253, 'learning_rate': 0.1976901851426852, 'max_depth': 14, 'min_split': 6, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:46,519] Trial 24 finished with value: 0.8266951758063614 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 267, 'learning_rate': 0.12010386249568439, 'max_depth': 18, 'min_split': 9, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:50,921] Trial 25 finished with value: 0.8266905174502023 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 219, 'learning_rate': 0.23313408038985478, 'max_depth': 10, 'min_split': 7, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:52,393] Trial 26 finished with value: 0.8241982969049881 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 56, 'learning_rate': 0.17459640443063157, 'max_depth': 11, 'min_split': 10, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:52,448] Trial 27 finished with value: 0.7269271619430935 and parameters: {'classifier': 'SVM', 'C': 0.15166369489645842, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:53,697] Trial 28 finished with value: 0.8154685374625003 and parameters: {'classifier': 'RandomForest', 'n_estimators': 186, 'max_depth': 17, 'min_split': 6, 'min_leaf': 3}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:14:59,913] Trial 29 finished with value: 0.8291780796392568 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 273, 'learning_rate': 0.11753252789932889, 'max_depth': 14, 'min_split': 9, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:15:04,104] Trial 30 finished with value: 0.8316749585406301 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 227, 'learning_rate': 0.25673418750002797, 'max_depth': 14, 'min_split': 8, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:15:07,559] Trial 31 finished with value: 0.8316842752529486 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 235, 'learning_rate': 0.25579160174036963, 'max_depth': 14, 'min_split': 8, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:15:10,813] Trial 32 finished with value: 0.8341764957981628 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 242, 'learning_rate': 0.2603140043782434, 'max_depth': 14, 'min_split': 8, 'min_leaf': 1}. Best is trial 16 with value: 0.835401643468053.
[I 2026-06-30 06:15:15,303] Trial 33 finished with value: 0.8379124974379041 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 238, 'learning_rate': 0.2711370706571583, 'max_depth': 15, 'min_split': 7, 'min_leaf': 1}. Best is trial 33 with value: 0.8379124974379041.
[I 2026-06-30 06:15:18,568] Trial 34 finished with value: 0.8441360612667003 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 188, 'learning_rate': 0.29718284552640606, 'max_depth': 17, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:18,600] Trial 35 finished with value: 0.7493385134253825 and parameters: {'classifier': 'LogisticRegression', 'C': 16.870229581936684, 'max_iter': 170}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:21,613] Trial 36 finished with value: 0.8291873963515753 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 193, 'learning_rate': 0.2962269964783143, 'max_depth': 18, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:24,551] Trial 37 finished with value: 0.8079452922652655 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 156, 'learning_rate': 0.26819571850877544, 'max_depth': 16, 'min_split': 5, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:24,605] Trial 38 finished with value: 0.7431149495965864 and parameters: {'classifier': 'SVM', 'C': 0.5020979243178963, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:24,638] Trial 39 finished with value: 0.7493385134253825 and parameters: {'classifier': 'LogisticRegression', 'C': 10.635440951368283, 'max_iter': 120}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:28,883] Trial 40 finished with value: 0.830417202377625 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 204, 'learning_rate': 0.2733928673756383, 'max_depth': 18, 'min_split': 6, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:32,247] Trial 41 finished with value: 0.806715486239216 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 233, 'learning_rate': 0.2544674398521213, 'max_depth': 15, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:35,974] Trial 42 finished with value: 0.8316749585406301 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 176, 'learning_rate': 0.2284960457560625, 'max_depth': 20, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:38,821] Trial 43 finished with value: 0.8304311774461027 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 245, 'learning_rate': 0.29999799624282075, 'max_depth': 13, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:43,532] Trial 44 finished with value: 0.7917342128309762 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 242, 'learning_rate': 0.23448751662972944, 'max_depth': 17, 'min_split': 5, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:43,563] Trial 45 finished with value: 0.7455931950733224 and parameters: {'classifier': 'LogisticRegression', 'C': 0.5730912965511499, 'max_iter': 423}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:43,677] Trial 46 finished with value: 0.7343758734417799 and parameters: {'classifier': 'SVM', 'C': 0.10155105755663112, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:46,906] Trial 47 finished with value: 0.8266951758063614 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 199, 'learning_rate': 0.27583689511232207, 'max_depth': 15, 'min_split': 6, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:48,381] Trial 48 finished with value: 0.8179747330761922 and parameters: {'classifier': 'RandomForest', 'n_estimators': 213, 'max_depth': 13, 'min_split': 7, 'min_leaf': 2}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:51,455] Trial 49 finished with value: 0.8179421245830771 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 170, 'learning_rate': 0.25021364361110005, 'max_depth': 11, 'min_split': 4, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:55,496] Trial 50 finished with value: 0.8192231725268787 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 260, 'learning_rate': 0.2880228842447424, 'max_depth': 16, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:15:58,858] Trial 51 finished with value: 0.8241982969049881 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 225, 'learning_rate': 0.252109819754214, 'max_depth': 14, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:01,960] Trial 52 finished with value: 0.8229591741666201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 239, 'learning_rate': 0.2653925989132328, 'max_depth': 13, 'min_split': 9, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:05,014] Trial 53 finished with value: 0.825451394711834 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 222, 'learning_rate': 0.278983500217187, 'max_depth': 15, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:09,468] Trial 54 finished with value: 0.8291827379954162 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 280, 'learning_rate': 0.24417709818072464, 'max_depth': 12, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:13,514] Trial 55 finished with value: 0.8204622952652468 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 286, 'learning_rate': 0.22440601089992046, 'max_depth': 17, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:15,255] Trial 56 finished with value: 0.8179700747200328 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 182, 'learning_rate': 0.2633620012629331, 'max_depth': 4, 'min_split': 9, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:16,911] Trial 57 finished with value: 0.8217107347159335 and parameters: {'classifier': 'RandomForest', 'n_estimators': 246, 'max_depth': 14, 'min_split': 7, 'min_leaf': 2}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:22,235] Trial 58 finished with value: 0.8216827845789778 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 210, 'learning_rate': 0.1875977994669771, 'max_depth': 15, 'min_split': 6, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:22,311] Trial 59 finished with value: 0.7942450668008273 and parameters: {'classifier': 'SVM', 'C': 30.93956563476083, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:22,341] Trial 60 finished with value: 0.7493385134253825 and parameters: {'classifier': 'LogisticRegression', 'C': 4.923323586027353, 'max_iter': 996}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:26,218] Trial 61 finished with value: 0.8279156651200924 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 173, 'learning_rate': 0.22021298109120274, 'max_depth': 20, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:29,487] Trial 62 finished with value: 0.8266905174502023 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 228, 'learning_rate': 0.28300063384268986, 'max_depth': 19, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:33,536] Trial 63 finished with value: 0.8279482736132073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 148, 'learning_rate': 0.2410561288915, 'max_depth': 19, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:36,908] Trial 64 finished with value: 0.8154778541748188 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 180, 'learning_rate': 0.2667218440112732, 'max_depth': 12, 'min_split': 7, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:38,692] Trial 65 finished with value: 0.7531397320513538 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 117, 'learning_rate': 0.2879547810880598, 'max_depth': 13, 'min_split': 2, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:42,002] Trial 66 finished with value: 0.8192091974584009 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 196, 'learning_rate': 0.2561580526592589, 'max_depth': 16, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:46,565] Trial 67 finished with value: 0.8304218607337842 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 216, 'learning_rate': 0.21192718490987048, 'max_depth': 19, 'min_split': 8, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:50,702] Trial 68 finished with value: 0.8304218607337842 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 261, 'learning_rate': 0.2285536820188795, 'max_depth': 14, 'min_split': 6, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:54,772] Trial 69 finished with value: 0.831670300184471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 234, 'learning_rate': 0.19875360873460535, 'max_depth': 15, 'min_split': 9, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:16:56,512] Trial 70 finished with value: 0.8167262936255054 and parameters: {'classifier': 'RandomForest', 'n_estimators': 252, 'max_depth': 16, 'min_split': 7, 'min_leaf': 2}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:17:02,940] Trial 71 finished with value: 0.8266951758063614 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 161, 'learning_rate': 0.1942691607259072, 'max_depth': 15, 'min_split': 10, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:17:07,307] Trial 72 finished with value: 0.8267184675871578 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 234, 'learning_rate': 0.18083678441575474, 'max_depth': 14, 'min_split': 9, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.
[I 2026-06-30 06:17:11,347] Trial 73 finished with value: 0.8341718374420034 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 222, 'learning_rate': 0.2045293467883627, 'max_depth': 17, 'min_split': 9, 'min_leaf': 1}. Best is trial 34 with value: 0.8441360612667003.

In [32]:
print(f"Best Trial Parameters: {study.best_trial.params}")
print(f"Best Trial Value: {study.best_trial.value}")

Best Trial Parameters: {'classifier': 'GradientBoosting', 'n_estimators': 188, 'learning_rate': 0.29718284552640606, 'max_depth': 17, 'min_split': 7, 'min_leaf': 1}
Best Trial Value: 0.8441360612667003

In [33]:
from sklearn.metrics import accuracy_score,classification_report
bestModel = RandomForestClassifier(
    n_estimators= study.best_trial.params['n_estimators'],
    max_depth = study.best_trial.params['max_depth'],
    random_state = 42
)
bestModel.fit(X_train,y_train)
y_pred = bestModel.predict(x_test)
testAccuracy = accuracy_score(y_test,y_pred)
print(f"Test Accuracy: {testAccuracy}")

Test Accuracy: 0.7727272727272727

In [34]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_max_iter,params_min_leaf,params_min_split,params_n_estimators,state
0,0,0.750657,2026-06-30 06:13:29.083505,2026-06-30 06:13:32.452839,0 days 00:00:03.369334,NaN,GradientBoosting,NaN,NaN,0.292155,20.0,NaN,1.0,4.0,168.0,COMPLETE
1,1,0.819214,2026-06-30 06:13:32.454100,2026-06-30 06:13:37.134274,0 days 00:00:04.680174,NaN,GradientBoosting,NaN,NaN,0.050921,7.0,NaN,1.0,5.0,250.0,COMPLETE
2,2,0.749339,2026-06-30 06:13:37.135547,2026-06-30 06:13:37.159970,0 days 00:00:00.024423,42.661465,LogisticRegression,NaN,NaN,NaN,NaN,556.0,NaN,NaN,NaN,COMPLETE
3,3,0.758092,2026-06-30 06:13:37.162029,2026-06-30 06:13:37.249738,0 days 00:00:00.087709,1.410402,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.749339,2026-06-30 06:13:37.250820,2026-06-30 06:13:37.273830,0 days 00:00:00.023010,95.100083,LogisticRegression,NaN,NaN,NaN,NaN,864.0,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.826691,2026-06-30 06:18:41.603455,2026-06-30 06:18:46.936248,0 days 00:00:05.332793,NaN,GradientBoosting,NaN,NaN,0.183507,17.0,NaN,1.0,8.0,198.0,COMPLETE
96,96,0.824184,2026-06-30 06:18:46.937446,2026-06-30 06:18:52.092154,0 days 00:00:05.154708,NaN,GradientBoosting,NaN,NaN,0.157411,19.0,NaN,1.0,7.0,189.0,COMPLETE
97,97,0.760579,2026-06-30 06:18:52.093407,2026-06-30 06:18:52.152305,0 days 00:00:00.058898,3.725428,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.749339,2026-06-30 06:18:52.153707,2026-06-30 06:18:52.185476,0 days 00:00:00.031769,1.031408,LogisticRegression,NaN,NaN,NaN,NaN,329.0,NaN,NaN,NaN,COMPLETE
99,99,0.835411,2026-06-30 06:18:52.188230,2026-06-30 06:18:57.030078,0 days 00:00:04.841848,NaN,GradientBoosting,NaN,NaN,0.175365,15.0,NaN,1.0,8.0,205.0,COMPLETE

In [35]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
GradientBoosting      73
LogisticRegression    10
SVM                    9
RandomForest           8
Name: count, dtype: int64

In [36]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting      0.822113
LogisticRegression    0.748839
RandomForest          0.815157
SVM                   0.747004
Name: value, dtype: float64